In [51]:
# super simple NN in pure python with 1 layer

import numpy as np

training_set_inputs = np.array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1], [1, 1, 0], [0, 1, 1], [0, 1, 0], [1, 0, 0], [0, 0, 0]])
training_set_outputs = np.array([[1, 1, 1, 1, 0, 1, 1, 1, 0]]).T

In [58]:
np.random.seed(100)

# initialize weights with values between -1 and 1
W1 = 2 * np.random.random((3, 4)) - 1  
W2 = 2 * np.random.random((4, 1)) - 1  

print(W1.shape)
print(W2.shape)
print(W1)
print(W2)

(3, 4)
(4, 1)
[[ 0.08680988 -0.44326123 -0.15096482  0.68955226]
 [-0.99056229 -0.75686176  0.34149817  0.65170551]
 [-0.72658682  0.15018666  0.78264391 -0.58159576]]
[[-0.62934356]
 [-0.78324622]
 [-0.56060501]
 [ 0.95724757]]


In [59]:
def nn(inputs):
    output1 = 1 / (1 + np.exp(-(np.dot(inputs, W1))))
    output2 = 1 / (1 + np.exp(-(np.dot(output1, W2))))
    return output1, output2

In [60]:
# The derivative of the Sigmoid function.
# This is the gradient of the Sigmoid curve.
# It indicates how confident we are about the existing weight.
def sigmoid_derivative(x):
    return x * (1 - x)

In [62]:
for iteration in range(5000):
    output1, output2 = nn(training_set_inputs)
    
    layer2_error = training_set_outputs - output2
    layer2_delta = layer2_error * sigmoid_derivative(output2)

    layer1_error = np.dot(layer2_delta, W2.T)
    layer1_delta = layer1_error * sigmoid_derivative(output1)
    
    W2 += np.dot(output2.T, layer2_delta)
    W1 += np.dot(training_set_inputs.T, layer1_delta)
    
    #if not iteration % 10:
#    print(error2[0])
#    print(sigmoid_derivative(output2[0]))
    
#    synaptic_weights += dot(training_set_inputs.T, (training_set_outputs - output) * output * (1 - output))

_, output2 = nn([0, 1, 1])
print(output2)
print(W1)
print(W2)

[0.85395182]
[[ 1.9160215  -2.51959751  2.83401147 -9.98057409]
 [-4.03603285  5.26168633 -5.89007223  4.14745801]
 [ 5.37008587 -7.27058253  8.22474481 14.43879665]]
[[ 0.04780451]
 [-0.10609815]
 [ 0.11654306]
 [ 1.63439564]]
